name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2

    - name: Login no DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}} 
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    

    
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: lucasjjgg/ps-visio-extra:${{github.run_number}}

